import type { NextConfig } from "next";

// SEO: redirects from old WordPress URLs (generated by scripts/generate-redirects.js)
// eslint-disable-next-line @typescript-eslint/no-require-imports
const legacyRedirects = require("./redirects-config.js") as Array<{
  source: string;
  destination: string;
  permanent: boolean;
}>;

const nextConfig: NextConfig = {
  env: {
    ADMIN_PASS: process.env.ADMIN_PASS,
  },
  async redirects() {
    // Filter out self-referential redirects (source === destination) to prevent ERR_TOO_MANY_REDIRECTS
    return legacyRedirects.filter((r) => r.source !== r.destination);
  },
  images: {
    // Set to true only to debug "images not showing on Vercel" (bypasses optimization).
    // unoptimized: true,
    remotePatterns: [
      { protocol: "https", hostname: "sivanandayogavietnam.org", port: "", pathname: "/**" },
      { protocol: "https", hostname: "sivanandavn2.wpengine.com", port: "", pathname: "/**" },
      { protocol: "https", hostname: "images.unsplash.com", port: "", pathname: "/**" },
      { protocol: "https", hostname: "zjffxjmsumxcdmqslmhw.supabase.co", port: "", pathname: "/**" },
      { protocol: "https", hostname: "znmazjqhyjxacqjjzsuh.supabase.co", port: "", pathname: "/**" },
    ],
  },
};

export default nextConfig;
