import type { NextConfig } from "next";

// SEO: redirects from old WordPress URLs (generated by scripts/generate-redirects.js)
// eslint-disable-next-line @typescript-eslint/no-require-imports
const legacyRedirects = require("./redirects-config.js") as Array<{
  source: string;
  destination: string;
  permanent: boolean;
}>;

const nextConfig: NextConfig = {
  async redirects() {
    return legacyRedirects;
  },
  images: {
    remotePatterns: [
      { protocol: "https", hostname: "sivanandayogavietnam.org", pathname: "/**" },
      { protocol: "https", hostname: "sivanandavn2.wpengine.com", pathname: "/**" },
      { protocol: "https", hostname: "images.unsplash.com", pathname: "/**" },
      { protocol: "https", hostname: "zjffxjmsumxcdmqslmhw.supabase.co", pathname: "/**" },
    ],
  },
};

export default nextConfig;
